// <copyright file="DeviceServiceApi.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Api
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Threading.Tasks;
    using RestSharp;
    using Emby.ApiClient.Client;
    using Emby.ApiClient.Model;

    /// <summary>
    /// Provides a collection of service methods to interact with the API endpoints.
    /// </summary>
    public partial class DeviceServiceApi : IApiAccessor, IDeviceServiceApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DeviceServiceApi(ApiClient apiClient)
        {
            this.ApiClient = apiClient;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.ApiClient.RestClient.Options.BaseUrl?.ToString();
        }

        /// <summary>Gets the ApiClient object</summary>
        /// <value>An instance of the ApiClient</value>
        public ApiClient ApiClient { get; }

        /// <summary>
        /// Gets all devices
        /// </summary>
        /// <remarks>
        /// Requires authentication as administrator
        /// </remarks>
        /// <param name="sortOrder">Sort Order - Ascending,Descending (optional)</param>
        /// <returns>Task of ApiResponse (QueryResultDevicesDeviceInfo)</returns>
        public async Task<RestResponse<QueryResultDevicesDeviceInfo>> GetDevices(string sortOrder = null)
        {
            var request = new RestRequest("/Devices", Method.Get);

            if (sortOrder != null)
            {
                request.AddQueryParameter("SortOrder", this.ApiClient.ParameterToString(sortOrder));
            }

            // make the HTTP request
            var localVarResponse = await this.ApiClient.RestClient.ExecuteAsync<QueryResultDevicesDeviceInfo>(request).ConfigureAwait(false);
            return localVarResponse;
        }
    }
}
