// <copyright file="SyncServiceApi.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Api
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Threading.Tasks;
    using RestSharp;
    using Emby.ApiClient.Client;
    using Emby.ApiClient.Model;

    /// <summary>
    /// Provides a collection of service methods to interact with the API endpoints.
    /// </summary>
    public partial class SyncServiceApi : IApiAccessor, ISyncServiceApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SyncServiceApi(ApiClient apiClient)
        {
            this.ApiClient = apiClient;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.ApiClient.RestClient.Options.BaseUrl?.ToString();
        }

        /// <summary>Gets the ApiClient object</summary>
        /// <value>An instance of the ApiClient</value>
        public ApiClient ApiClient { get; }

        /// <summary>
        /// Gets sync jobs.
        /// </summary>
        /// <remarks>
        /// Requires authentication as user
        /// </remarks>
        /// <returns>Task of ApiResponse (QueryResultSyncJob)</returns>
        public async Task<RestResponse<QueryResultSyncJob>> GetSyncJobs()
        {
            var request = new RestRequest("/Sync/Jobs", Method.Get);

            // make the HTTP request
            var localVarResponse = await this.ApiClient.RestClient.ExecuteAsync<QueryResultSyncJob>(request).ConfigureAwait(false);
            return localVarResponse;
        }

        /// <summary>
        /// Gets sync jobs.
        /// </summary>
        /// <remarks>
        /// Requires authentication as user
        /// </remarks>
        /// <param name="body">SyncJobRequest: </param>
        /// <returns>Task of ApiResponse (SyncJobCreationResult)</returns>
        public async Task<RestResponse<SyncJobCreationResult>> PostSyncJobs(SyncJobRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
            {
                throw new ApiException("Missing required parameter 'body' when calling SyncServiceApi->PostSyncJobs");
            }

            var request = new RestRequest("/Sync/Jobs", Method.Post);

            if (body != null)
            {
                request.AddJsonBody(body);
            }

            // make the HTTP request
            var localVarResponse = await this.ApiClient.RestClient.ExecuteAsync<SyncJobCreationResult>(request).ConfigureAwait(false);
            return localVarResponse;
        }
    }
}
